from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import List, Optional
import io
from fpdf import FPDF

from ..database import get_db
from .. import models, schemas, auth

router = APIRouter(prefix="/api/reports", tags=["Reports & Exports"])

@router.get("", response_model=List[schemas.ReportOut])
def list_reports(
    project_id: Optional[int] = None,
    report_type: Optional[str] = None,
    current_user: models.User = Depends(auth.get_current_user),
    db: Session = Depends(get_db)
):
    query = db.query(models.Report)
    if project_id is not None:
        query = query.filter(models.Report.project_id == project_id)
    if report_type is not None:
        query = query.filter(models.Report.type == report_type)
    return query.all()

@router.post("", response_model=schemas.ReportOut, status_code=status.HTTP_201_CREATED)
def create_report(
    report_in: schemas.ReportCreate,
    current_user: models.User = Depends(auth.get_current_active_scrum_master),
    db: Session = Depends(get_db)
):
    db_report = models.Report(
        project_id=report_in.project_id,
        sprint_id=report_in.sprint_id,
        type=report_in.type,
        title=report_in.title,
        content=report_in.content
    )
    db.add(db_report)
    db.commit()
    db.refresh(db_report)
    return db_report

class ReportPDFGenerator(FPDF):
    def header(self):
        # Arial bold 14
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(79, 70, 229)  # Violet brand color
        self.cell(0, 10, 'SPRINTSENSE · AGILE REPORT', 0, 1, 'L')
        self.set_draw_color(226, 232, 240)
        self.line(10, 20, 200, 20)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by SprintSense AI', 0, 0, 'C')

@router.get("/{report_id}/pdf")
def download_report_pdf(
    report_id: int,
    current_user: models.User = Depends(auth.get_current_user),
    db: Session = Depends(get_db)
):
    report = db.query(models.Report).filter(models.Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
        
    pdf = ReportPDFGenerator()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font('Helvetica', 'B', 22)
    pdf.set_text_color(15, 23, 42)  # Charcoal
    pdf.cell(0, 15, report.title, 0, 1, 'L')
    
    # Metadata table
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(40, 7, "Report Type:", 0, 0)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 7, report.type, 0, 1)
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(40, 7, "Project:", 0, 0)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 7, report.project.name if report.project else "Unknown", 0, 1)
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(40, 7, "Sprint:", 0, 0)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 7, report.sprint.name if report.sprint else "N/A", 0, 1)
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(40, 7, "Created At:", 0, 0)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 7, report.created_at.strftime("%b %d, %Y %H:%M:%S"), 0, 1)
    pdf.ln(10)
    
    # Render sections depending on content JSON structure
    content = report.content
    if isinstance(content, dict):
        for section_title, section_val in content.items():
            # Section Header
            pdf.set_font('Helvetica', 'B', 14)
            pdf.set_text_color(79, 70, 229)
            pdf.cell(0, 10, str(section_title).replace('_', ' ').title(), 0, 1, 'L')
            pdf.ln(1)
            
            # Section Body
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(51, 65, 85)
            
            if isinstance(section_val, list):
                for item in section_val:
                    # Bullet point
                    pdf.cell(5, 6, chr(149), 0, 0)  # Bullet character
                    pdf.multi_cell(0, 6, str(item))
            elif isinstance(section_val, dict):
                for k, v in section_val.items():
                    pdf.set_font('Helvetica', 'B', 10)
                    pdf.cell(40, 6, f"{str(k).title()}:", 0, 0)
                    pdf.set_font('Helvetica', '', 10)
                    pdf.multi_cell(0, 6, str(v))
            else:
                pdf.multi_cell(0, 6, str(section_val))
            pdf.ln(5)
    else:
        pdf.set_font('Helvetica', '', 11)
        pdf.set_text_color(51, 65, 85)
        pdf.multi_cell(0, 6, str(content))
        
    # Output PDF as byte string
    pdf_bytes = pdf.output()
    
    # Create byte stream response
    buffer = io.BytesIO(pdf_bytes)
    headers = {
        'Content-Disposition': f'attachment; filename="{report.title.replace(" ", "_")}.pdf"'
    }
    return StreamingResponse(buffer, headers=headers, media_type='application/pdf')
