import { createFileRoute, Navigate } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth";
import { Sparkles, Download, FileBarChart, Users, ShieldAlert, TrendingUp } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports · SprintSense AI" },
      { name: "description", content: "Downloadable sprint, developer, AI risk, and performance reports." },
      { property: "og:title", content: "Reports · SprintSense AI" },
      { property: "og:description", content: "Downloadable AI-generated sprint reports." },
    ],
  }),
  component: ReportsPage,
});

const reports = [
  { title: "Sprint Report", desc: "Full sprint burn-up, scope, and completion.", icon: FileBarChart, color: "from-violet-500 to-fuchsia-500" },
  { title: "Developer Report", desc: "Individual velocity, quality, and load.", icon: Users, color: "from-sky-500 to-cyan-500" },
  { title: "AI Risk Report", desc: "Risk trends, top causes, forecast accuracy.", icon: ShieldAlert, color: "from-amber-500 to-rose-500" },
  { title: "Performance Report", desc: "Cycle time, throughput, and quality index.", icon: TrendingUp, color: "from-emerald-500 to-teal-500" },
];

function ReportsPage() {
  const user = useAuth();
  if (user === undefined) return null;
  if (!user) return <Navigate to="/login" />;
  return (
    <AppShell>
      <div className="space-y-6">
        <div>
          <div className="text-xs font-semibold text-primary uppercase tracking-widest flex items-center gap-1.5">
            <Sparkles className="h-3.5 w-3.5" /> Insights
          </div>
          <h1 className="font-display text-4xl font-bold mt-1">Reports</h1>
          <p className="text-muted-foreground mt-1">Generated by AI · exportable as PDF or CSV.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {reports.map((r) => (
            <div key={r.title} className="glass rounded-2xl p-6 relative overflow-hidden group hover:-translate-y-1 transition-all">
              <div className={`absolute -top-16 -right-16 h-48 w-48 rounded-full bg-gradient-to-br ${r.color} opacity-20 blur-3xl`} />
              <div className="relative flex items-start gap-4">
                <div className={`grid h-12 w-12 place-items-center rounded-xl bg-gradient-to-br ${r.color} text-white shadow-lg shrink-0`}>
                  <r.icon className="h-6 w-6" />
                </div>
                <div className="min-w-0 flex-1">
                  <h3 className="font-display text-xl font-bold">{r.title}</h3>
                  <p className="text-sm text-muted-foreground mt-1">{r.desc}</p>
                  <div className="mt-4 flex gap-2">
                    <Button size="sm" className="gradient-primary text-white" onClick={() => toast.success(`${r.title} exported (PDF)`)}>
                      <Download className="h-3.5 w-3.5 mr-1.5" /> PDF
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => toast.success(`${r.title} exported (CSV)`)}>
                      <Download className="h-3.5 w-3.5 mr-1.5" /> CSV
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </AppShell>
  );
}
